### PR TITLE
Add frameworks

### PR DESCRIPTION
**Pull request by larufa**
### 検証用の Vagrant 環境を作成
---
#### 使用手順
* make を叩いて laravel をインストール
* vagrant フォルダに移動して vagrant up
* 192.168.33.80 にアクセスして Laravel のテストページが見えたらOK

### CODE REVIEW

**Comment by kanap0nta** [comment]
vagrant up後、
Warning: Authentication failure. Retrying...
が繰り返されたのちタイムアウトします

**Comment by larufa** [comment]
直した

**Comment by larufa** [comment]
https://github.com/co-mmun/commun/pull/2/commits/f96ccd202f39d5a000680fcec342650bf71b0b4e

**Comment by kanap0nta** [comment]
vagrant up後、下記エラーが出力されます。

Vagrant cannot forward the specified ports on this VM, since they
would collide with some other application that is already listening
on these ports. The forwarded port to 8080 is already in use
on the host machine.

To fix this, modify your current project's Vagrantfile to use another
port. Example, where '1234' would be replaced by a unique host port:

  config.vm.network :forwarded_port, guest: 80, host: 1234

Sometimes, Vagrant will attempt to auto-correct this for you. In this
case, Vagrant was unable to. This is usually because the guest machine
is in a state which doesn't allow modifying port forwarding. You could
try 'vagrant reload' (equivalent of running a halt followed by an up)
so vagrant can attempt to auto-correct this upon booting. Be warned
that any unsaved work might be lost.

**Comment by larufa** [comment]
別の仮想マシンが立ち上がってるので、それ消しちゃってください from virtualbox。たぶん8888ポート使ってるやつがいる

**Comment by kanap0nta** [comment]
LGTM

**Comment by larufa** [comment]
thx

**Pull request merged**
